// Code generated by genconst; DO NOT EDIT.
package rest

const (
	ServiceClassification        = "classification"
	ServiceClassificationStream  = "classification_stream"
	ServiceEmbedding             = "embedding"
	ServiceEmbeddingStream       = "embedding_stream"
	ServiceFaceDetection         = "face_detection"
	ServiceFaceDetectionStream   = "face_detection_stream"
	ServiceFaceRecognition       = "face_recognition"
	ServiceFaceRecognitionStream = "face_recognition_stream"
)

// Generated 8 constants.

// NOTE: run `go generate ./pkg/server/rest/service` to update.
