// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GatewayService bridges Wails IPC calls to the core Lumen SDK systems.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConfig returns the current configuration details.
 */
export function GetConfig(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(264284223).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetMetrics returns general metrics of the gateway client.
 */
export function GetMetrics(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3823256750).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetNodes retrieves list of discovered nodes converted to UI DTOs.
 */
export function GetNodes(): $CancellablePromise<$models.FrontendNodeInfo[]> {
    return $Call.ByID(1471395474).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetStatus returns the running status, uptime, and node statistics.
 */
export function GetStatus(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3435149367).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetTasks lists all tasks grouped by service.
 */
export function GetTasks(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1314098997).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Quit stops the gateway core and exits the application cleanly.
 */
export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(636981804);
}

/**
 * Reload stops current services, reloads configuration from disk, and restarts services.
 */
export function Reload(): $CancellablePromise<void> {
    return $Call.ByID(2014115306);
}

/**
 * SaveConfig saves the configuration to disk and triggers service hot-reload.
 */
export function SaveConfig(cfg: { [_ in string]?: any }): $CancellablePromise<void> {
    return $Call.ByID(2329579528, cfg);
}

/**
 * Start starts the Lumen client and REST API server.
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(3185748433);
}

/**
 * Stop stops the client and REST server.
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(4087007115);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.FrontendNodeInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
