// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FrontendNodeInfo is a simplified DTO representation of a node for the React UI.
 */
export class FrontendNodeInfo {
    "id": string;
    "name": string;
    "address": string;
    "status": string;
    "tasks": string[];

    /** Creates a new FrontendNodeInfo instance. */
    constructor($$source: Partial<FrontendNodeInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("tasks" in $$source)) {
            this["tasks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FrontendNodeInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): FrontendNodeInfo {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tasks" in $$parsedSource) {
            $$parsedSource["tasks"] = $$createField4_0($$parsedSource["tasks"]);
        }
        return new FrontendNodeInfo($$parsedSource as Partial<FrontendNodeInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
