# Brave Configuration - Server Deployment
# Designed for high-performance server environments with ample resources

# Service Discovery - Aggressive configuration
discovery:
    enabled: true
    service_type: "_lumen._tcp"
    domain: "local"
    scan_interval: 15s              # Frequent scans for rapid node discovery
    node_timeout: 2m                 # Short timeout for quick failure detection
    max_nodes: 50                    # High limit for enterprise deployments

# Connection - High-performance settings
connection:
    dial_timeout: 3s                 # Fast connection establishment
    keep_alive: 15s                 # Shorter keep-alive for connection recycling
    max_message_size: 8388608       # 8MB limit for large payloads
    insecure: false
    compression: true               # Save bandwidth

# Server - Full service stack
server:
    rest:
        enabled: true
        host: "0.0.0.0"
        port: 8080
        cors: true                  # Enable CORS for web interfaces
        timeout: 15s                # Fast timeout for responsive services

    mcp:
        enabled: true                # Enable MCP for enterprise integration

    llmtools:
        enabled: true                # Enable LLM tools for advanced features

# Load Balancer - High-performance configuration
load_balancer:
    strategy: "least_connections"    # Optimize for load distribution
    cache_enabled: true             # Enable caching for performance
    cache_ttl: 2m                   # Short cache for fresher results
    health_check: true             # Aggressive health monitoring
    check_interval: 5s             # Frequent health checks
    default_timeout: 15s           # Fast default timeout

# Logging - Comprehensive logging
logging:
    level: "info"                   # Standard logging level
    format: "json"                  # JSON format for structured logging
    output: "stdout"                # Can be redirected to log aggregation

# Monitoring - Full observability
monitoring:
    enabled: true                   # Enable comprehensive monitoring
    metrics_port: 9091              # Standard metrics port
    health_port: 9092               # Standard health check port

# Optimizations for Server Deployments:
# - Frequent service discovery for dynamic environments
# - High node limit for enterprise scale
# - Fast connection timeouts for responsive services
# - Large message size support
# - Least connections load balancing for optimal distribution
# - Aggressive health monitoring for reliability
# - Short cache TTL for fresh results
# - Full service stack enabled
# - Comprehensive monitoring and observability
# - Structured logging for log aggregation systems
