name: Release

on:
    push:
        tags:
            - "v*"

env:
    GO_VERSION: "1.24"

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                  go-version: ${{ env.GO_VERSION }}

            - name: Cache Go modules
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cache/go-build
                      ~/go/pkg/mod
                  key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                  restore-keys: |
                      ${{ runner.os }}-go-

            - name: Download dependencies
              run: go mod download

            - name: Run tests
              run: go test -v -race -coverprofile=coverage.out ./...

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v3
              with:
                  file: ./coverage.out
                  token: ${{ secrets.CODECOV_TOKEN }}

    build:
        name: Build
        runs-on: ubuntu-latest
        needs: test
        strategy:
            matrix:
                goos: [linux, darwin, windows]
                goarch: [amd64, arm64]
                exclude:
                    - goos: windows
                      goarch: arm64
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v4
              with:
                  go-version: "1.21"

            - name: Build
              env:
                  GOOS: ${{ matrix.goos }}
                  GOARCH: ${{ matrix.goarch }}
                  VERSION: ${{ github.ref_name }}
              run: |
                  mkdir -p dist
                  CGO_ENABLED=0 go build -ldflags="-X 'main.Version=$VERSION'" -o dist/lumenhubd ./cmd/lumenhubd
                  CGO_ENABLED=0 go build -ldflags="-X 'main.Version=$VERSION'" -o dist/lumenhub ./cmd/lumenhub

            - name: Create archive
              run: |
                  cd dist
                  if [ "${{ matrix.goos }}" = "windows" ]; then
                    7z a lumenhub-${{ matrix.goos }}-${{ matrix.goarch }}.zip *
                  else
                    tar -czf lumenhub-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz *
                  fi

            - uses: actions/upload-artifact@v4
              with:
                  name: lumenhub-${{ matrix.goos }}-${{ matrix.goarch }}
                  path: dist/lumenhub-*.*

    release:
        name: Create Release
        runs-on: ubuntu-latest
        needs: [test, build]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Download all artifacts
              uses: actions/download-artifact@v4
              with:
                  path: artifacts

            - name: List downloaded artifacts
              run: find artifacts -type f -name "*.tar.gz" -o -name "*.zip"

            - name: Get version
              id: version
              run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

            - name: Create release notes
              id: release_notes
              run: |
                  # Generate release notes from commit history since last tag
                  PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
                  if [ -n "$PREV_TAG" ]; then
                    NOTES=$(git log --pretty=format:"- %s (%h)" $PREV_TAG..HEAD)
                  else
                    NOTES=$(git log --pretty=format:"- %s (%h)")
                  fi
                  {
                    echo 'notes<<EOF'
                    echo "$NOTES"
                    echo 'EOF'
                  } >> "$GITHUB_OUTPUT"

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ steps.version.outputs.VERSION }}
                  name: Release ${{ steps.version.outputs.VERSION }}
                  body: |
                      # Lumen Hub ${{ steps.version.outputs.VERSION }}

                      ## 🚀 Installation

                      ### Download Binaries
                      ```bash
                      # Linux AMD64
                      curl -L https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.VERSION }}/lumenhub-${{ steps.version.outputs.VERSION }}-linux-amd64.tar.gz | tar xz
                      sudo mv lumenhubd lumenhub /usr/local/bin/

                      # macOS AMD64
                      curl -L https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.VERSION }}/lumenhub-${{ steps.version.outputs.VERSION }}-darwin-amd64.tar.gz | tar xz
                      sudo mv lumenhubd lumenhub /usr/local/bin/

                      # Linux ARM64
                      curl -L https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.VERSION }}/lumenhub-${{ steps.version.outputs.VERSION }}-linux-arm64.tar.gz | tar xz
                      sudo mv lumenhubd lumenhub /usr/local/bin/

                      # macOS ARM64
                      curl -L https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.VERSION }}/lumenhub-${{ steps.version.outputs.VERSION }}-darwin-arm64.tar.gz | tar xz
                      sudo mv lumenhubd lumenhub /usr/local/bin/
                      ```



                      ## 📋 Changes
                      ${{ steps.release_notes.outputs.notes }}

                      ---
                      📖 [Documentation](https://github.com/${{ github.repository }}/blob/main/README.md)
                  draft: false
                  prerelease: false
                  files: |
                      artifacts/**/*.tar.gz
                      artifacts/**/*.zip

            - name: Update latest tag
              if: startsWith(github.ref, 'refs/tags/')
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git tag -f latest
                  git push -f origin latest
